version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker1
      MYSQL_DATABASE: Skarbnik3
    volumes:
      - ./db-mount-entrypoint/account-setup.sql:/docker-entrypoint-initdb.d/account-setup.sql
      - ./db-mount-entrypoint/data-dump.sql:/docker-entrypoint-initdb.d/data-dump.sql
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: skarbnik-hackathon
    volumes:
      - .:/skarbnik-hackathon
    depends_on:
      - db
    command: bash -c "./wait-for-it.sh -t 0 db:3306 -- python manage.py makemigrations skarbnik && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    