version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: skarbnik-hackathon
    volumes:
      - .:/skarbnik-hackathon
    ports:
      - "8000:8000"
    extra_hosts:
      - "db:192.168.8.100"